DROP TABLE M_USER CASCADE CONSTRAINT PURGE;
DROP TABLE M_DIVISI CASCADE CONSTRAINT PURGE;
DROP TABLE M_PERTANYAAN CASCADE CONSTRAINT PURGE;
DROP TABLE M_SESSION CASCADE CONSTRAINT PURGE;
DROP TABLE R_PROFILE CASCADE CONSTRAINT PURGE;
DROP TABLE R_PERTANYAAN CASCADE CONSTRAINT PURGE;
DROP TABLE H_RESPONSE CASCADE CONSTRAINT PURGE;
DROP TABLE D_RESPONSE CASCADE CONSTRAINT PURGE;
DROP TABLE SETTINGS CASCADE CONSTRAINT PURGE;

CREATE TABLE M_USER 
(
    ID NUMBER(10) PRIMARY KEY,
    DIVISI VARCHAR2(100) NOT NULL,
    NAMA VARCHAR2(200) NOT NULL,
    USERNAME VARCHAR2(200) NOT NULL,
    PASSWORD VARCHAR2(200) NOT NULL,
    ROLE NUMBER(2) NOT NULL,
    STATUS NUMBER(2) NOT NULL
);

CREATE TABLE M_DIVISI
(
    ID NUMBER(10) PRIMARY KEY,
    ALIAS VARCHAR2(100),
    NAMA VARCHAR2(200) NOT NULL
);

CREATE TABLE M_PERTANYAAN
(
    ID NUMBER(10) PRIMARY KEY,
    TEXT VARCHAR2(250) NOT NULL
);

CREATE TABLE M_SESSION
(
    ID NUMBER(10) PRIMARY KEY,
    NAMA VARCHAR2(200) NOT NULL,
    MULAI DATE,
    AKHIR DATE,
    STATUS NUMBER(2) NOT NULL
);

CREATE TABLE R_PROFILE
(
    ID NUMBER(10) PRIMARY KEY,
    ID_SESSION NUMBER(10),
    DIVISI_TANYA NUMBER(10),
    DIVISI_DITANYA NUMBER(10)
);

CREATE TABLE R_PERTANYAAN
(
    ID NUMBER(10) PRIMARY KEY,
    ID_PROFILE NUMBER(10),
    ID_PERTANYAAN NUMBER(10)
);

CREATE TABLE H_RESPONSE
(
    ID NUMBER(10) PRIMARY KEY,
    ID_USER NUMBER(10),
    ID_SESSION NUMBER(10),
    ID_PROFILE NUMBER(10),
    WAKTU DATE
);

CREATE TABLE D_RESPONSE
(
    ID NUMBER(10) PRIMARY KEY,
    ID_HRESPONSE NUMBER(10),
    ID_PERTANYAAN NUMBER(10),
    JAWABAN NUMBER(10)
);

CREATE TABLE SETTINGS
(
    ACTIVE_SESSION NUMBER(10)
);

-- AUTO INCREMENT USER
DROP SEQUENCE user_id_seq;
DROP TRIGGER user_bi;

CREATE SEQUENCE user_id_seq;
CREATE TRIGGER user_bi
BEFORE INSERT ON M_USER
FOR EACH ROW
BEGIN
    SELECT user_id_seq.nextval
    INTO :new.ID
    FROM dual;
END;
/

-- AUTO INCREMENT PERTANYAAN
DROP SEQUENCE pertanyaan_id_seq;
DROP TRIGGER pertanyaan_bi;

CREATE SEQUENCE pertanyaan_id_seq;
CREATE TRIGGER pertanyaan_bi
BEFORE INSERT ON M_PERTANYAAN
FOR EACH ROW
BEGIN
    SELECT pertanyaan_id_seq.nextval
    INTO :new.ID
    FROM dual;
END;
/

-- AUTO INCREMENT SESSION
DROP SEQUENCE session_id_seq;
DROP TRIGGER session_bi;

CREATE SEQUENCE session_id_seq;
CREATE TRIGGER session_bi
BEFORE INSERT ON M_SESSION
FOR EACH ROW
BEGIN
    SELECT session_id_seq.nextval
    INTO :new.ID
    FROM dual;
END;
/

-- AUTO INCREMENT DIVISI
DROP SEQUENCE divisi_id_seq;
DROP TRIGGER divisi_bi;

CREATE SEQUENCE divisi_id_seq;
CREATE TRIGGER divisi_bi
BEFORE INSERT ON M_DIVISI
FOR EACH ROW
BEGIN
    SELECT divisi_id_seq.nextval
    INTO :new.ID
    FROM dual;
END;
/

