DROP TABLE M_USER CASCADE CONSTRAINT PURGE;
DROP TABLE M_DIVISI CASCADE CONSTRAINT PURGE;
DROP TABLE M_PERTANYAAN CASCADE CONSTRAINT PURGE;
DROP TABLE M_SESSION CASCADE CONSTRAINT PURGE;
DROP TABLE R_PROFILE CASCADE CONSTRAINT PURGE;
DROP TABLE R_PERTANYAAN CASCADE CONSTRAINT PURGE;
DROP TABLE H_RESPONSE CASCADE CONSTRAINT PURGE;
DROP TABLE D_RESPONSE CASCADE CONSTRAINT PURGE;
DROP TABLE SETTINGS CASCADE CONSTRAINT PURGE;

CREATE TABLE M_USER 
(
    ID NUMBER(10) PRIMARY KEY,
    DIVISI VARCHAR2(20) NOT NULL,
    NAMA VARCHAR2(200) NOT NULL,
    USERNAME VARCHAR2(200) NOT NULL,
    PASSWORD VARCHAR2(200) NOT NULL,
    ROLE NUMBER(2) NOT NULL,
    STATUS NUMBER(2) NOT NULL
);

CREATE TABLE M_DIVISI
(
    ALIAS VARCHAR2(20) PRIMARY KEY,
    NAMA VARCHAR2(200) NOT NULL
);

CREATE TABLE M_PERTANYAAN
(
    ID NUMBER(10) PRIMARY KEY,
    TEXT VARCHAR2(250) NOT NULL,
    STATUS NUMBER(2) NOT NULL
);

CREATE TABLE M_SESSION
(
    ID NUMBER(10) PRIMARY KEY,
    NAMA VARCHAR2(200) NOT NULL,
    MULAI DATE,
    AKHIR DATE,
    STATUS NUMBER(2) NOT NULL
);

CREATE TABLE R_PROFILE
(
    ID NUMBER(10) PRIMARY KEY,
    ID_SESSION NUMBER(10),
    DIVISI_TANYA VARCHAR2(20),
    DIVISI_DITANYA VARCHAR2(20)
);

CREATE TABLE R_PERTANYAAN
(
    ID NUMBER(10) PRIMARY KEY,
    ID_PROFILE NUMBER(10),
    ID_PERTANYAAN NUMBER(10)
);

CREATE TABLE H_RESPONSE
(
    ID NUMBER(10) PRIMARY KEY,
    ID_USER NUMBER(10),
    ID_PROFILE NUMBER(10)
);

CREATE TABLE D_RESPONSE
(
    ID NUMBER(10) PRIMARY KEY,
    ID_HRESPONSE NUMBER(10),
    ID_PERTANYAAN NUMBER(10),
    JAWABAN NUMBER(10),
    SARAN VARCHAR2(200)
);

-- AUTO INCREMENT USER
DROP SEQUENCE user_id_seq;
DROP TRIGGER user_bi;

CREATE SEQUENCE user_id_seq;
CREATE TRIGGER user_bi
BEFORE INSERT ON M_USER
FOR EACH ROW
BEGIN
    SELECT user_id_seq.nextval
    INTO :new.ID
    FROM dual;
END;
/

-- AUTO INCREMENT PERTANYAAN
DROP SEQUENCE pertanyaan_id_seq;
DROP TRIGGER pertanyaan_bi;

CREATE SEQUENCE pertanyaan_id_seq;
CREATE TRIGGER pertanyaan_bi
BEFORE INSERT ON M_PERTANYAAN
FOR EACH ROW
BEGIN
    SELECT pertanyaan_id_seq.nextval
    INTO :new.ID
    FROM dual;
END;
/

-- AUTO INCREMENT SESSION
DROP SEQUENCE session_id_seq;
DROP TRIGGER session_bi;

CREATE SEQUENCE session_id_seq;
CREATE TRIGGER session_bi
BEFORE INSERT ON M_SESSION
FOR EACH ROW
BEGIN
    SELECT session_id_seq.nextval
    INTO :new.ID
    FROM dual;
END;
/

-- AUTO INCREMENT PROFILE
DROP SEQUENCE profile_id_seq;
DROP TRIGGER profile_bi;

CREATE SEQUENCE profile_id_seq;
CREATE TRIGGER profile_bi
BEFORE INSERT ON R_PROFILE
FOR EACH ROW
BEGIN
    SELECT profile_id_seq.nextval
    INTO :new.ID
    FROM dual;
END;
/

-- AUTO INCREMENT PERTANYAAN
DROP SEQUENCE pertanyaan_id_seq;
DROP TRIGGER pertanyaan_bi;

CREATE SEQUENCE pertanyaan_id_seq;
CREATE TRIGGER pertanyaan_bi
BEFORE INSERT ON R_PERTANYAAN
FOR EACH ROW
BEGIN
    SELECT pertanyaan_id_seq.nextval
    INTO :new.ID
    FROM dual;
END;
/

-- AUTO INCREMENT HRESPONSE
DROP SEQUENCE hresponse_id_seq;
DROP TRIGGER hresponse_bi;

CREATE SEQUENCE hresponse_id_seq;
CREATE TRIGGER hresponse_bi
BEFORE INSERT ON H_RESPONSE
FOR EACH ROW
BEGIN
    SELECT hresponse_id_seq.nextval
    INTO :new.ID
    FROM dual;
END;
/

-- AUTO INCREMENT DRESPONSE
DROP SEQUENCE dresponse_id_seq;
DROP TRIGGER dresponse_bi;

CREATE SEQUENCE dresponse_id_seq;
CREATE TRIGGER dresponse_bi
BEFORE INSERT ON D_RESPONSE
FOR EACH ROW
BEGIN
    SELECT dresponse_id_seq.nextval
    INTO :new.ID
    FROM dual;
END;
/

-- Seeding
insert into M_DIVISI (ALIAS, NAMA) values ('AS', 'Asahan');
insert into M_DIVISI (ALIAS, NAMA) values ('KEU', 'Keuangan');

insert into M_USER (DIVISI, NAMA, USERNAME, PASSWORD, ROLE, STATUS) values ('KEU', 'Calvin Adhikang', 'calvin', 'calvin', 1, 1);
insert into M_USER (DIVISI, NAMA, USERNAME, PASSWORD, ROLE, STATUS) values ('KEU', 'Angeline Valencia', 'angel', 'angel', 1, 1);
insert into M_USER (DIVISI, NAMA, USERNAME, PASSWORD, ROLE, STATUS) values ('AS', 'Ivander Wijaya', 'ivander', 'ivander', 1, 1);
insert into M_USER (DIVISI, NAMA, USERNAME, PASSWORD, ROLE, STATUS) values ('ADMIN', 'Yuki Adhikang', 'yukibara', 'yukibara', 0, 1);

insert into M_PERTANYAAN values (1, 'Berapa tingkat kepuasan terhadap divisi ini ?', 1);
insert into M_PERTANYAAN values (2, 'Berapa tingkat kecepatan pelayanan divisi ini ?', 1);
insert into M_PERTANYAAN values (3, 'Berapa tingkat tingkat kekompakan divisi ini ?', 0);

commit;